
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-hausarzt
  name: ms-hausarzt
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-hausarzt
    spec:
      containers:
      - image: ms-hausarzt-frontend
        name: ms-hausarzt-frontend
        ports:
        - containerPort: 80
      - image: ms-hausarzt-backend
        name: ms-hausarzt-backend
        ports:
        - containerPort: 8080
      - image: mongo
        name: ms-hausarzt-db
        volumeMounts:
          - mountPath: /data/db
            name: db
            subPath: hausarzt-db-v1
      restartPolicy: Always 
      volumes:
        - name: db
          gcePersistentDisk:
            pdName: ms-hausarzt
            fsType: ext4
status: {}