version: '3'
services:
  frontend:
    build: client/.
    ports:
      - 8080:80
  backend:
    build: server/.
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
