version: '3'
services:
  frontend:
    build: client/.
    ports:
      - 80:80
  backend:
    build: server/.
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
