apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\timst\Documents\Master\Projekt_Brunsmann\MS_Hausarzt\kompose-windows-amd64.exe
      convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
