apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\timst\Documents\Master\Projekt_Brunsmann\MS_Hausarzt\kompose-windows-amd64.exe
      convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\timst\Documents\Master\Projekt_Brunsmann\MS_Hausarzt\kompose-windows-amd64.exe
          convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - args:
        - ng
        - serve
        image: frontend
        name: frontend
        ports:
        - containerPort: 4200
        resources: {}
        workingDir: /client
      restartPolicy: Always
status: {}
