apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-hausarzt
  name: ms-hausarzt
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: ms-hausarzt
status:
  loadBalancer: {}